config/routes.rb
RailsTest::Application.routes.draw do

  resources :session_statuses

  resources :session_operations

  resources :sessions

	get 'users/exists' => "users#exists"
	
  resources :products

  resources :product_statuses

  resources :refund_types

  resources :guarantees

  resources :guarantee_companies

  resources :borrowers

  resources :phones

  resources :emails

  resources :users

  resources :roles

  resources :bank_accounts

  resources :bank_card_types

  resources :bank_branches

  resources :banks

  resources :districts

  resources :cities

  resources :provinces

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	has_many :bank_branches
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
	has_one :bank_card_type
	has_one :bank
end

app/models/bank_branch.rb
class BankBranch < ActiveRecord::Base
	belongs_to :bank
	has_one :province
	has_one :city
end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :province
	has_many :districts
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :city
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user
end

app/models/guarantee.rb
class Guarantee < ActiveRecord::Base
	has_one :guarantee_company
	belongs_to :product
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :borrower
	has_many :guarantees
	has_one :refund_type
	has_one :product_status
end

app/models/province.rb
class Province < ActiveRecord::Base
	has_many :cities
	has_many :districts, through: :cities
end

app/models/refund_type.rb
class RefundType < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :session_operation
	belongs_to :session_status
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	include BCrypt
	
	has_many :emails
	has_many :phones
	has_and_belongs_to_many :roles
	accepts_nested_attributes_for :emails
	accepts_nested_attributes_for :phones
	accepts_nested_attributes_for :roles

	#def login_pass
	#	@login_pass ||= Password.new(login_pass)
	#end

	#def login_pass=(p)
	#	@login_pass = Password.create(p)
	#	self.login_pass = @login_pass
	#end

	#def pay_pass
	#  @pay_pass ||= Password.new(pay_pass)
	#end

	#def pay_pass=(p)
	#	@pay_pass = Password.create(p)
	# self.pay_pass = @pay_pass
	#end
	
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  before_action :set_borrower, only: [:show, :edit, :update, :destroy]

  # GET /borrowers
  # GET /borrowers.json
  def index
    @borrowers = Borrower.all
  end

  # GET /borrowers/1
  # GET /borrowers/1.json
  def show
  end

  # GET /borrowers/new
  def new
    @borrower = Borrower.new
  end

  # GET /borrowers/1/edit
  def edit
  end

  # POST /borrowers
  # POST /borrowers.json
  def create
    @borrower = Borrower.new(borrower_params)

    respond_to do |format|
      if @borrower.save
        format.html { redirect_to @borrower, notice: 'Borrower was successfully created.' }
        format.json { render action: 'show', status: :created, location: @borrower }
      else
        format.html { render action: 'new' }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrowers/1
  # PATCH/PUT /borrowers/1.json
  def update
    respond_to do |format|
      if @borrower.update(borrower_params)
        format.html { redirect_to @borrower, notice: 'Borrower was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowers/1
  # DELETE /borrowers/1.json
  def destroy
    @borrower.destroy
    respond_to do |format|
      format.html { redirect_to borrowers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrower
      @borrower = Borrower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrower_params
      params.require(:borrower).permit(:name)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/borrowers/_form.html.erb
<%= form_for(@borrower) do |f| %>
  <% if @borrower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrower.errors.count, "error") %> prohibited this borrower from being saved:</h2>

      <ul>
      <% @borrower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borrowers/edit.html.erb
<h1>Editing borrower</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrower %> |
<%= link_to 'Back', borrowers_path %>

app/views/borrowers/index.html.erb
<h1>Listing borrowers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @borrowers.each do |borrower| %>
      <tr>
        <td><%= borrower.name %></td>
        <td><%= link_to 'Show', borrower %></td>
        <td><%= link_to 'Edit', edit_borrower_path(borrower) %></td>
        <td><%= link_to 'Destroy', borrower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Borrower', new_borrower_path %>

app/views/borrowers/new.html.erb
<h1>New borrower</h1>

<%= render 'form' %>

<%= link_to 'Back', borrowers_path %>

app/views/borrowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @borrower.name %>
</p>

<%= link_to 'Edit', edit_borrower_path(@borrower) %> |
<%= link_to 'Back', borrowers_path %>