config/routes.rb
RailsTest::Application.routes.draw do

  resources :session_statuses

  resources :session_operations

  resources :sessions

	get 'users/exists' => "users#exists"
	
  resources :products

  resources :product_statuses

  resources :refund_types

  resources :guarantees

  resources :guarantee_companies

  resources :borrowers

  resources :phones

  resources :emails

  resources :users

  resources :roles

  resources :bank_accounts

  resources :bank_card_types

  resources :bank_branches

  resources :banks

  resources :districts

  resources :cities

  resources :provinces

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	has_many :bank_branches
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
	has_one :bank_card_type
	has_one :bank
end

app/models/bank_branch.rb
class BankBranch < ActiveRecord::Base
	belongs_to :bank
	has_one :province
	has_one :city
end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :province
	has_many :districts
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :city
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user
end

app/models/guarantee.rb
class Guarantee < ActiveRecord::Base
	has_one :guarantee_company
	belongs_to :product
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :borrower
	has_many :guarantees
	has_one :refund_type
	has_one :product_status
end

app/models/province.rb
class Province < ActiveRecord::Base
	has_many :cities
	has_many :districts, through: :cities
end

app/models/refund_type.rb
class RefundType < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :session_operation
	belongs_to :session_status
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	include BCrypt
	
	has_many :emails
	has_many :phones
	has_and_belongs_to_many :roles
	accepts_nested_attributes_for :emails
	accepts_nested_attributes_for :phones
	accepts_nested_attributes_for :roles

	#def login_pass
	#	@login_pass ||= Password.new(login_pass)
	#end

	#def login_pass=(p)
	#	@login_pass = Password.create(p)
	#	self.login_pass = @login_pass
	#end

	#def pay_pass
	#  @pay_pass ||= Password.new(pay_pass)
	#end

	#def pay_pass=(p)
	#	@pay_pass = Password.create(p)
	# self.pay_pass = @pay_pass
	#end
	
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bank_account }
      else
        format.html { render action: 'new' }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:account)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for(@bank_account) do |f| %>
  <% if @bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h2>

      <ul>
      <% @bank_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<h1>Editing bank_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank_account %> |
<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/index.html.erb
<h1>Listing bank_accounts</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_accounts.each do |bank_account| %>
      <tr>
        <td><%= bank_account.account %></td>
        <td><%= link_to 'Show', bank_account %></td>
        <td><%= link_to 'Edit', edit_bank_account_path(bank_account) %></td>
        <td><%= link_to 'Destroy', bank_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank account', new_bank_account_path %>

app/views/bank_accounts/new.html.erb
<h1>New bank_account</h1>

<%= render 'form' %>

<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @bank_account.account %>
</p>

<%= link_to 'Edit', edit_bank_account_path(@bank_account) %> |
<%= link_to 'Back', bank_accounts_path %>