config/routes.rb
RailsTest::Application.routes.draw do

  resources :session_statuses

  resources :session_operations

  resources :sessions

	get 'users/exists' => "users#exists"
	
  resources :products

  resources :product_statuses

  resources :refund_types

  resources :guarantees

  resources :guarantee_companies

  resources :borrowers

  resources :phones

  resources :emails

  resources :users

  resources :roles

  resources :bank_accounts

  resources :bank_card_types

  resources :bank_branches

  resources :banks

  resources :districts

  resources :cities

  resources :provinces

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	has_many :bank_branches
end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
	has_one :bank_card_type
	has_one :bank
end

app/models/bank_branch.rb
class BankBranch < ActiveRecord::Base
	belongs_to :bank
	has_one :province
	has_one :city
end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :province
	has_many :districts
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :city
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user
end

app/models/guarantee.rb
class Guarantee < ActiveRecord::Base
	has_one :guarantee_company
	belongs_to :product
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :borrower
	has_many :guarantees
	has_one :refund_type
	has_one :product_status
end

app/models/province.rb
class Province < ActiveRecord::Base
	has_many :cities
	has_many :districts, through: :cities
end

app/models/refund_type.rb
class RefundType < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :session_operation
	belongs_to :session_status
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	include BCrypt
	
	has_many :emails
	has_many :phones
	has_and_belongs_to_many :roles
	accepts_nested_attributes_for :emails
	accepts_nested_attributes_for :phones
	accepts_nested_attributes_for :roles

	#def login_pass
	#	@login_pass ||= Password.new(login_pass)
	#end

	#def login_pass=(p)
	#	@login_pass = Password.create(p)
	#	self.login_pass = @login_pass
	#end

	#def pay_pass
	#  @pay_pass ||= Password.new(pay_pass)
	#end

	#def pay_pass=(p)
	#	@pay_pass = Password.create(p)
	# self.pay_pass = @pay_pass
	#end
	
end

app/controllers/refund_types_controller.rb
class RefundTypesController < ApplicationController
  before_action :set_refund_type, only: [:show, :edit, :update, :destroy]

  # GET /refund_types
  # GET /refund_types.json
  def index
    @refund_types = RefundType.all
  end

  # GET /refund_types/1
  # GET /refund_types/1.json
  def show
  end

  # GET /refund_types/new
  def new
    @refund_type = RefundType.new
  end

  # GET /refund_types/1/edit
  def edit
  end

  # POST /refund_types
  # POST /refund_types.json
  def create
    @refund_type = RefundType.new(refund_type_params)

    respond_to do |format|
      if @refund_type.save
        format.html { redirect_to @refund_type, notice: 'Refund type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @refund_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @refund_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /refund_types/1
  # PATCH/PUT /refund_types/1.json
  def update
    respond_to do |format|
      if @refund_type.update(refund_type_params)
        format.html { redirect_to @refund_type, notice: 'Refund type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @refund_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /refund_types/1
  # DELETE /refund_types/1.json
  def destroy
    @refund_type.destroy
    respond_to do |format|
      format.html { redirect_to refund_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_refund_type
      @refund_type = RefundType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def refund_type_params
      params.require(:refund_type).permit(:name)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/refund_types_helper.rb
module RefundTypesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/refund_types/_form.html.erb
<%= form_for(@refund_type) do |f| %>
  <% if @refund_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@refund_type.errors.count, "error") %> prohibited this refund_type from being saved:</h2>

      <ul>
      <% @refund_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/refund_types/edit.html.erb
<h1>Editing refund_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @refund_type %> |
<%= link_to 'Back', refund_types_path %>

app/views/refund_types/index.html.erb
<h1>Listing refund_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @refund_types.each do |refund_type| %>
      <tr>
        <td><%= refund_type.name %></td>
        <td><%= link_to 'Show', refund_type %></td>
        <td><%= link_to 'Edit', edit_refund_type_path(refund_type) %></td>
        <td><%= link_to 'Destroy', refund_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Refund type', new_refund_type_path %>

app/views/refund_types/new.html.erb
<h1>New refund_type</h1>

<%= render 'form' %>

<%= link_to 'Back', refund_types_path %>

app/views/refund_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @refund_type.name %>
</p>

<%= link_to 'Edit', edit_refund_type_path(@refund_type) %> |
<%= link_to 'Back', refund_types_path %>